name: PHP Code Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Validate PHP syntax
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml
